### ISSUE TITLE
类名自动添加前缀

### ISSUE THREAD

**Issue by gitMyPtro** [yican008/wx2swan#18]
之前的css类名
![image](https://user-images.githubusercontent.com/42534582/47691944-09c0bd00-dc2f-11e8-99be-c3f6c518cf50.png)

之后的css类名
![image](https://user-images.githubusercontent.com/42534582/47691979-252bc800-dc2f-11e8-91bc-a1be0534257e.png)

**Comment by zhengjiaqi** [comment]
能详细描述一下你的需求吗

**Comment by zhengjiaqi** [comment]
百度小程序的自定义组件中会自动在css前添加命名空间防止全局样式污染
