### ISSUE TITLE
转化不了，会报错，该怎么解决？

### ISSUE THREAD

**Issue by vipxiaocao** [yican008/wx2swan#5]
![qq 20180928180631](https://user-images.githubusercontent.com/25164037/46202366-3c824780-c349-11e8-825c-36dde4226692.png)

**Comment by vipxiaocao** [comment]
已解决了，node的版本过低，原来是8.2.0的，换成了8.12.0。

**Comment by zhengjiaqi** [comment]
1.1.14版本加入了es6转码，解决了低版本node报错的问题
